#logging:
#  level:
#    root: DEBUG
#
server:
  port: 8080


spring:
  application:
    name: auth-service
  datasource:
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:root}
    url: ${DB_URL:jdbc:mysql://localhost:3306/omnio}
  jpa:
    show-sql: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.MySQL8Dialect}
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
jwt:
  issuer: localhost:9000
  valid-seconds:
    access: 300
    refresh: 1500
#logging:
#  level:
#    web: DEBUG